---
params:
  index_name: ""
subtitle: Index Risk Metrics
editor_options:
  chunk_output_type: console
output: 
  html_document:
    theme: flatly
    highlight: tango
    includes:
        in_header: header.html
---

```{r, init_chunk, echo = FALSE, message = FALSE, warning = FALSE}
createdDate <- gsub(" 0", " ",format(Sys.Date(), "%B %d, %Y"))
idPath <- ".."

library('RODBC')
library('quantmod')
library('PerformanceAnalytics')

library('tidyverse')
library('lubridate')
library('ggthemes')
library('reshape2')
library('viridis')
library('DT')
library('ggrepel')

library('scales')
library('sysfonts')
library('showtext')
library('ggradar') # remotes::install_github("ricardo-bion/ggradar")

font_add_google("Kanit", "kanit")
#font_add_google("Lobster Two", "lobstertwo")
font_add_google("Roboto", "roboto")
showtext_auto()

options(stringsAsFactors = FALSE)
options("scipen"=100)

iName <- params$index_name

source("C:/stockviz/r/config.r")

lcon <- odbcDriverConnect(sprintf("Driver={ODBC Driver 17 for SQL Server};Server=%s;Database=%s;Uid=%s;Pwd=%s;", ldbserver, ldbname, ldbuser, ldbpassword), case = "nochange", believeNRows = TRUE)

asofDt <- sqlQuery(lcon, "select max(time_stamp) from bhav_index")[[1]]
startDate <- as.Date("2010-01-01")

iDf1 <- sqlQuery(lcon, sprintf("select time_stamp, px_close from bhav_index where index_name='%s' and time_stamp >= '%s' and time_stamp <= '%s'", iName, startDate, asofDt))
iXts <- xts(iDf1[,2], iDf1[,1])

retXts <- monthlyReturn(iXts)
retWeekly <- weeklyReturn(iXts)
retDaily <- dailyReturn(iXts)
retAnn <- annualReturn(iXts)

names(retXts) <- c(iName)
names(retWeekly) <- c(iName)
names(retDaily) <- c(iName)
names(retAnn) <- c(iName)

```

---
title: `r iName`
date: `r createdDate`
---

```{r, perf_chunk, echo = FALSE, message = FALSE, warning = FALSE}
cumRetChart <- chart.CumReturns(retDaily, main = iName, legend.loc = 'topleft')
drawdownChart <- chart.Drawdown(retDaily, main = iName, legend.loc = 'bottomleft')

toPlotAnn <- data.frame(retAnn*100)
toPlotAnn$Y <- year(index(retAnn))

maxYear <- length(unique(toPlotAnn$Y))
toPlotAnn <- melt(toPlotAnn, id='Y')
minRet <- min(toPlotAnn$value)
toPlotAnn$Y <- factor(toPlotAnn$Y, levels = unique(toPlotAnn$Y))

annRetPlot <- ggplot(toPlotAnn, aes(x=Y, y=value, fill=variable)) +
	theme_economist() +
	geom_bar(stat = "identity", position = position_dodge()) +
	geom_text_repel(aes(label = sprintf('%.2f', value)), position = position_dodge(0.9)) +
	scale_fill_viridis(discrete = TRUE) +
	labs(x = "Year", y="Returns (%)", fill="", color="", size="", title=sprintf("%s", iName), subtitle=sprintf("Annual Returns [%s:%s]", first(index(retDaily)), last(index(retDaily)))) +
	annotate("text", x=maxYear, y=minRet, label = "@StockViz", hjust=1, vjust=0, col="white", cex=6, fontface = "bold", alpha = 0.8)
	
years <- iDf1 %>% mutate(Y = year(time_stamp)) %>% group_by(Y) %>% summarize(ctr = n()) %>% filter(ctr > 20) %>% select(Y) %>% arrange(Y)
years <- years$Y

annualRets <- data.frame(Y=0, R=0.0)
dailyByYrXts<-NULL
for(i in 1:(length(years)-1)){
	yr<-years[i]
	yrSeries <- iXts[toString(yr)]
	drets <- dailyReturn(yrSeries)
	icol <- cumprod(1+drets)
	dcol<-as.Date(sprintf("2000-%s", strftime(index(yrSeries), "%m-%d")))
	dailyByYrXts <- merge.xts(dailyByYrXts, xts(icol, dcol))
	annualRets <- rbind(annualRets, c(yr, as.numeric(Return.cumulative(drets))))
}
dailyByYrXts<-na.locf(dailyByYrXts)

annualRets <- annualRets[-1,]
annualRets$Y <- as.integer(annualRets$Y)
annualRets$R <- as.numeric(annualRets$R)

i<-length(years)
yr<-years[i]

yrSeries <- iXts[toString(yr)]
drets <- dailyReturn(yrSeries)
icol <- cumprod(1+drets)
dcol<-as.Date(sprintf("2000-%s", strftime(index(yrSeries), "%m-%d")))
lastCol <- xts(icol, dcol)
dailyByYrXts <- merge.xts(dailyByYrXts, lastCol)
dailyByYrXts[sprintf("%s/%s", first(index(lastCol)), last(index(lastCol))), ncol(dailyByYrXts)] <- na.locf(dailyByYrXts[sprintf("%s/%s", first(index(lastCol)), last(index(lastCol))), ncol(dailyByYrXts)])

names(dailyByYrXts) <- sapply(years, function(X) toString(X))

dailyByYear <- data.frame(dailyByYrXts)
dailyByYear$T <- index(dailyByYrXts)

toPlot <- melt(dailyByYear, id='T')
toPlot$variable <- gsub("X", "", as.character(toPlot$variable))
#toPlot$T <- factor(toPlot$T, levels=unique(toPlot$T))

greys <- colorRampPalette(c("#FFFDD0", "black"))(length(years))
toPlot$color <- greys[as.integer(toPlot$variable) - min(years) + 1]
toPlot$sz <- (as.integer(toPlot$variable) - min(years) + 1)/(2*length(years))
toPlot[toPlot$variable == toString(max(years)),]$sz <- 1.5

minYr <- annualRets[annualRets$R == min(annualRets$R),1]
maxYr <- annualRets[annualRets$R == max(annualRets$R),1]

minYr2 <- annualRets[annualRets$R == min(annualRets[annualRets$R > min(annualRets$R),2]), 1]
maxYr2 <- annualRets[annualRets$R == max(annualRets[annualRets$R < max(annualRets$R),2]), 1]

toPlot[as.integer(toPlot$variable) == minYr,]$sz <- 1
toPlot[as.integer(toPlot$variable) == maxYr,]$sz <- 1

toPlot[as.integer(toPlot$variable) == minYr2,]$sz <- 0.75
toPlot[as.integer(toPlot$variable) == maxYr2,]$sz <- 0.75

toPlot[as.integer(toPlot$variable) == minYr,]$color <- "darkred"
toPlot[as.integer(toPlot$variable) == maxYr,]$color <- "darkgreen"

toPlot[as.integer(toPlot$variable) == minYr2,]$color <- "darkred"
toPlot[as.integer(toPlot$variable) == maxYr2,]$color <- "darkgreen"

toPlot$label <- NA
toPlot[as.integer(toPlot$variable) == minYr,]$label[nrow(toPlot[as.integer(toPlot$variable) == minYr,])] <- minYr
toPlot[as.integer(toPlot$variable) == maxYr,]$label[nrow(toPlot[as.integer(toPlot$variable) == maxYr,])] <- maxYr
toPlot[as.integer(toPlot$variable) == minYr2,]$label[nrow(toPlot[as.integer(toPlot$variable) == minYr2,])] <- minYr2
toPlot[as.integer(toPlot$variable) == maxYr2,]$label[nrow(toPlot[as.integer(toPlot$variable) == maxYr2,])] <- maxYr2
toPlot[as.integer(toPlot$variable) == max(years) & !is.na(toPlot$value),]$label[nrow(toPlot[as.integer(toPlot$variable) == max(years) & !is.na(toPlot$value),])] <- max(years)

dateBreaks <- index(dailyByYrXts)
day(dateBreaks) <- days_in_month(dateBreaks)
dateBreaks <- unique(dateBreaks)

fanPlot <- ggplot(toPlot, aes(x=T, y=value, group=variable)) +
	theme_economist() +
	theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
	geom_line(aes(color=color, size=sz)) +
	scale_color_identity() +
	scale_size_identity() +
	scale_x_date(breaks = dateBreaks, date_labels="%b-%d", expand=c(0, 0)) +
	geom_label_repel(aes(label = label), alpha=0.5) +
	labs(x='', y='growth of Rs. 1', title=iName, subtitle=sprintf("%d:%s", min(years), asofDt)) +
	annotate("text", x=toPlot$T[1], y=min(toPlot$value, na.rm=T), label = "@StockViz", hjust=0, vjust=0, col="white", cex=6, fontface = "bold", alpha = 0.8)	
```

```{r, returns_chart_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE, fig.height=6, fig.width=12}
cat("\n\n### Annual Returns", "\n\n")
print(fanPlot)
cat("\n\n")
print(annRetPlot)
cat("\n\n### Cumulative Returns", "\n\n")
print(cumRetChart)
cat("\n\n### Drawdowns", "\n\n")
print(drawdownChart)
```

```{r, metrics_radar_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE, fig.height=12, fig.width=12}
metricMap <- read.csv(paste0(idPath, "/metric_map.csv"))

indices <- sqlQuery(lcon, sprintf("select distinct index_name from index_capm where time_stamp = '%s'", asofDt))[,1]

statsDf <- sqlQuery(lcon, sprintf("select INDEX_NAME, ID, VAL from INDEX_CAPM where INDEX_NAME in ('%s')", paste(indices, collapse="','"))) 

rankTibs <- statsDf %>% 
	pivot_wider(names_from=ID, values_from=VAL) %>% 
	mutate_at(vars(-INDEX_NAME), rank) 

metricDf <- statsDf %>% filter(INDEX_NAME == iName) %>%
	inner_join(rankTibs %>% filter(INDEX_NAME == iName) %>% pivot_longer(!INDEX_NAME, names_to='ID', values_to='VAL') %>% select(ID, VAL), by='ID') %>%
	inner_join(metricMap, by='ID') %>%
	mutate(METRIC = paste0(DESC, ' (', ID, ')'), VAL = round(VAL.x, 5)) %>%
	rename(SCORE = VAL.y) %>%
	select(METRIC, VAL, SCORE) %>%
	as.data.frame()

cat("\n\n\n### Performance Metrics")
mfMetricsDT <- datatable(metricDf, rownames = F, class = 'cell-border stripe', filter='none', colnames = c("", names(metricDf)[-1]), options = list(dom = 't', pageLength = 30, ordering=F))
htmltools::tagList(print(mfMetricsDT))

statsTibs <- statsDf %>% 
	pivot_wider(names_from=ID, values_from=VAL) %>% 
	mutate_at(vars(-INDEX_NAME), rescale)
				
avgTibs <- statsTibs %>% summarize_at(vars(-INDEX_NAME), mean, na.rm=T) %>% mutate(INDEX_NAME='Average')

toPlot <- statsTibs %>% filter(INDEX_NAME==iName) %>% mutate(INDEX_NAME = 'INDEX') %>% bind_rows(avgTibs) %>% as.data.frame()
			
rplot <- ggradar(plot.data = toPlot,
		font.radar = "roboto",
		grid.label.size = 5,  # Affects the grid annotations (0%, 50%, etc.)
		axis.label.size = 8, # Afftects the names of the variables
		group.point.size = 3   # Simply the size of the point 
	  ) +
	labs(title = iName, tag=paste("@StockViz", asofDt)) + 
	theme(
	  plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
	  panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
	  plot.title.position = "plot", # slightly different from default
	  plot.title = element_text(
			family = "noto", 
			size = 38,
			color = "#2a475e"
		),
	  plot.tag = element_text(
			family = "kanit", 
			size = 16,
			color = "lightgrey",
		),
	  plot.tag.position = "bottom"
	) +
	theme(
		legend.position = c(1, 0),  
		legend.justification = c(1, 0),
		legend.text = element_text(size = 24, family = "roboto"),
		legend.key = element_rect(fill = NA, color = NA),
		legend.background = element_blank()
	)
	
print(rplot)
```

