---
title: Mutual Fund Surveillance
subtitle: StockViz
editor_options:
  chunk_output_type: console
output: 
  html_document:
    theme: flatly
    highlight: tango
    includes:
        in_header: header.html
---

```{r dt_chunk, include=FALSE}

createdDate <- gsub(" 0", " ",format(Sys.Date(), "%B %d, %Y"))

```

---
date: `r createdDate`
---

```{r, calc_chunk, echo = FALSE, message = FALSE, warning = FALSE}

library('RODBC')
library('quantmod')
library('PerformanceAnalytics')
library('xtable')
library('knitr')
library('kableExtra')
library('DT')

options(stringsAsFactors = FALSE)
options("scipen"=100)

source("c:/stockviz/r/config.r")

lcon <- odbcDriverConnect(sprintf("Driver={ODBC Driver 17 for SQL Server};Server=%s;Database=%s;Uid=%s;Pwd=%s;", ldbserver, ldbname, ldbuser, ldbpassword), case = "nochange", believeNRows = TRUE)

asofDt<-sqlQuery(lcon, "select max(as_of) from mf_nav_history")[[1]]
startDate <- as.Date("2018-01-01")

analyzeFunds <- function(schemeCodes, indices){
	retXts <- NULL
	fundNames <- c()
	
	for(i in 1:length(schemeCodes)){
		fname <- sqlQuery(lcon, sprintf("select scheme_name from mf_nav_history where scheme_code=%d and as_of='%s'", schemeCodes[i], asofDt))[[1]]
		fundNames <- c(fundNames, fname)
		
		iDf <- sqlQuery(lcon, sprintf("select as_of, nav from mf_nav_history where scheme_code=%d and as_of >= '%s' and as_of <= '%s'", schemeCodes[i], startDate, asofDt))
		iXts <- xts(iDf[,2], iDf[,1])
		retXts <- merge.xts(retXts, monthlyReturn(iXts))
	}

	names(retXts) <- schemeCodes

	iRetXts <- NULL
	for(iName in indices){
		iDf <- sqlQuery(lcon, sprintf("select time_stamp, px_close from BHAV_INDEX where index_name='%s' and time_stamp >= '%s' and time_stamp <= '%s'", iName, startDate, asofDt))
		iXts <- xts(iDf[,2], iDf[,1])
		iRetXts <- merge.xts(iRetXts, monthlyReturn(iXts))
	}

	names(iRetXts) <- indices

	######################

	fitList <- list()
	for(benchIndex in 1:length(indices)){
		mfFits <- NULL
		for(mfIndex in 1:ncol(retXts)){
			allXts <- merge(retXts[, mfIndex], iRetXts[, 1:benchIndex])
			allXts <- na.omit(allXts)
			
			benchNames <- paste0("B", seq(1:benchIndex))
			names(allXts) <- c('A', benchNames)
			
			linearFit <- lm(formula(paste0("A ~ ", paste(benchNames, collapse='+'))), data.frame(allXts))
			lmCoeffs <- c(round(as.numeric(linearFit$coeff), 5), round(100*summary(linearFit)$adj.r.squared, 0))
			
			mfFits <- rbind.data.frame(mfFits, lmCoeffs)
		}
		names(mfFits) <- c('ALPHA', indices[1:benchIndex], 'ar2%')
		mfFits$FUND <- fundNames
		
		fitList <- append(fitList, list(mfFits))
	}

	mfDT <- list()
	for(i in 1:length(fitList)){
		X <- fitList[[i]]
		mfDT[[i]] <- datatable(X[, c(ncol(X), 1:(ncol(X)-1))], rownames = F, class = 'cell-border stripe', filter='none', options = list(dom = 't', pageLength = 30))
	}
	
	return(mfDT)
}

largecapFunds <- sqlQuery(lcon, sprintf("select scheme_code, min(as_of) stdt, max(as_of) ltdt from mf_nav_history where 
										scheme_name like '%%large%%direct%%' 
										and scheme_name like '%%growth%%' 
										and scheme_name not like '%%idcw%%' 
										and scheme_name not like '%%bonus%%' 
										and scheme_name not like '%%mid%%' 
										and scheme_name not like '%%small%%' 
										and scheme_name not like '%%tax%%' 
										and as_of >= '%s' 
										group by scheme_code", startDate))
largecapFunds <- largecapFunds[largecapFunds$stdt <= startDate+180 & largecapFunds$ltdt >= asofDt-5,]

largemfDT <- analyzeFunds(largecapFunds$scheme_code, c('NIFTY 100 TR', 'NIFTY100 QUALITY 30 TR', 'NIFTY500 VALUE 50 TR'))

midcapFunds <- sqlQuery(lcon, sprintf("select scheme_code, min(as_of) stdt, max(as_of) ltdt from mf_nav_history where 
										scheme_name like '%%mid%%cap%%direct%%' 
										and scheme_name like '%%growth%%' 
										and scheme_name not like '%%idcw%%' 
										and scheme_name not like '%%bonus%%' 
										and scheme_name not like '%%large%%' 
										and scheme_name not like '%%small%%' 
										and scheme_name not like '%%tax%%' 
										and as_of >= '%s' 
										group by scheme_code", startDate))
midcapFunds <- midcapFunds[midcapFunds$stdt <= startDate+180 & midcapFunds$ltdt >= asofDt-5,]

midmfDT <- analyzeFunds(midcapFunds$scheme_code, c('NIFTY MIDCAP 150 TR', 'NIFTY MIDCAP150 QUALITY 50 TR', 'NIFTY500 VALUE 50 TR'))

```{r, large_cap_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE}
cat("### Large-cap Funds", "\n")

htmltools::tagList(
	lapply(largemfDT, print)
)
```

```{r, mid_cap_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE}
cat("### Mid-cap Funds", "\n")

htmltools::tagList(
	lapply(midmfDT, print)
)
```